# Generated by Django 2.2.5 on 2019-09-07 22:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_byte_arr', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/input'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OutputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_byte_arr', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/output'), upload_to='')),
            ],
        ),
    ]
