# Generated by Django 2.2.5 on 2019-09-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputimage',
            old_name='image_byte_arr',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='outputimage',
            old_name='image_byte_arr',
            new_name='image',
        ),
    ]
