# Generated by Django 2.2.5 on 2019-09-07 23:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20190907_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='input'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='outputimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='output'), upload_to=''),
        ),
    ]
